version: '3.7'

services:
  db:
    image: postgres:14.3-alpine
    # restart: always
    env_file:
      - ./confs/enabled/db.env
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ava_user"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  moodle:
    # image: 'ctezlifrn/moodle:3.11.10-php7.4-002'
    image: 'ctezlifrn/moodle:4.0.4-php8.0-002'
    # restart: always
    ports:
      - '8000:80'
    env_file:
      - ./confs/enabled/db.env
      - ./confs/enabled/moodle.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Plugins
      # - './src/php/moodle__block_newblock:/var/www/html/blocks/newblock'
      - './src/php/moodle__block_presenca:/var/www/html/blocks/presenca'

      # Data
      - './volumes/moodledata:/var/moodledata'
    depends_on:
      db:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --silent --fail http://avazlapp:80/ | grep AVA_do_Zona_Leste || exit 1"]
    #   interval: 3s
    #   timeout: 1s
    #   start_period: 1s
    #   retries: 30

