#!/usr/bin/env bash
source _/functions

if [[ `docker container ls | grep sead_db-1` ]]; then 
  echo_info "O banco já está em execução"
else
  docker compose up -d $@ $SERVICE_NAME
  _/$SERVICE_NAME/wait
fi
